/*---------------------------------------------------------- 
MASV: 47.01.104.041
HO TEN: NGUYEN DUC AN
LAB: 03 
NGAY: 03/04/2024 ----------------------------------------------------------*/ 

CREATE DATABASE QLSV
USE QLSV

CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)

CREATE TABLE LOP(
	MALOP VARCHAR(20) NOT NULL,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),
	CONSTRAINT PK_LOP PRIMARY KEY(MALOP)
)

CREATE TABLE SINHVIEN (
	MASV NVARCHAR(20)  NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME, 
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY (MAX),
	CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV)
)
GO

--i
CREATE PROC SP_INS_ENCRYPT_SINHVIEN
	@MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MATKHAU VARBINARY(MAX)
AS
BEGIN
    INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU)
END
declare @MK varchar(100) = 'minhnhut123'
declare @MK_HASH varbinary(MAX)
set @MK_HASH = HASHBYTES('MD5', @MK)
EXEC SP_INS_ENCRYPT_SINHVIEN 'SV01', 'NGUYEN VAN A', '1990-01-01', 
'280 AN DUONG VUONG', 'CNTT-K35', 'NVA', @MK_HASH
GO

--ii
CREATE PROC SP_INS_ENCRYPT_NHANVIEN
	@MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONG VARBINARY(MAX),
    @TENDN NVARCHAR(100),
    @MATKHAU VARBINARY(MAX)
AS
BEGIN    
	INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MATKHAU)
END
GO

CREATE SYMMETRIC KEY SK01
	WITH ALGORITHM = AES_256
	ENCRYPTION BY PASSWORD = '47.01.104.041';
GO

DECLARE @MATKHAU VARCHAR(50) = 'ducan'
DECLARE @MATKHAU_HASH VARBINARY(MAX)
SET @MATKHAU_HASH = CONVERT(VARBINARY(MAX), HASHBYTES('SHA1', @MATKHAU), 1)
DECLARE @LUONG BIGINT = 3000000
DECLARE @LUONG_HASH VARBINARY(MAX) 
OPEN SYMMETRIC KEY SK01
DECRYPTION BY PASSWORD = '47.01.104.041';
SET @LUONG_HASH = ENCRYPTBYKEY(KEY_GUID('SK01'), CONVERT(VARBINARY(MAX), @LUONG))
EXEC SP_INS_ENCRYPT_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', @LUONG_HASH, 'NVA', @MATKHAU_HASH
GO

--iii
CREATE PROC SP_SEL_ENCRYPT_NHANVIEN
AS
BEGIN
	SELECT MANV, HOTEN, EMAIL,LUONG FROM NHANVIEN
END