/*---------------------------------------------------------- 
MASV: 47.01.104.041
HO TEN: NGUYEN DUC AN
LAB: 03 
NGAY: 03/04/2024 ----------------------------------------------------------*/ 

CREATE DATABASE QLSV
USE QLSV

CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
)

CREATE TABLE LOP(
	MALOP VARCHAR(20) NOT NULL,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),
	CONSTRAINT PK_LOP PRIMARY KEY(MALOP)
)

CREATE TABLE SINHVIEN (
	MASV NVARCHAR(20)  NOT NULL,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME, 
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY (MAX),
	CONSTRAINT PK_SINHVIEN PRIMARY KEY(MASV)
)
GO
--i
CREATE PROC SP_INS_SINHVIEN
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(32)
AS
BEGIN
    DECLARE @MATKHAU_HASH VARBINARY(16)
    SET @MATKHAU_HASH = CONVERT(VARBINARY(16), HASHBYTES('MD5', @MATKHAU), 1)

    INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MATKHAU_HASH)
END

EXEC SP_INS_SINHVIEN 'SV01', 'NGUYEN VAN A', '1990-01-01', '280 AN DUONG VUONG', 'CNTT-K35', 'NVA', '123456'
GO

--ii
CREATE SYMMETRIC KEY SK01
	WITH ALGORITHM = AES_256
	ENCRYPTION BY PASSWORD = '47.01.104.041';
GO

CREATE PROC SP_INS_NHANVIEN
    @MANV NVARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONG BIGINT,
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(32)
AS
BEGIN
    DECLARE @MATKHAU_HASH VARBINARY(16)
    SET @MATKHAU_HASH = CONVERT(VARBINARY(16), HASHBYTES('SHA1', @MATKHAU), 1)
	
	DECLARE @LUONG_HASH VARBINARY(MAX) 
	
	OPEN SYMMETRIC KEY SK01
	DECRYPTION BY PASSWORD = '47.01.104.041';
	SET @LUONG_HASH = ENCRYPTBYKEY(KEY_GUID('SK01'), CONVERT(VARBINARY(16), @LUONG))
    
	INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG_HASH, @TENDN, @MATKHAU_HASH)
	
	CLOSE SYMMETRIC KEY SK01;
END

EXEC SP_INS_NHANVIEN 'NV01', 'NGUYEN VAN A', 'NVA@', 3000000, 'NVA', 'abcd12'
GO

--iii
CREATE PROC SP_SEL_NHANVIEN
AS
BEGIN
	OPEN SYMMETRIC KEY SK01
	DECRYPTION BY PASSWORD = '47.01.104.041';
	SELECT MANV, HOTEN, EMAIL,
	CONVERT(BIGINT, DECRYPTBYKEY(LUONG)) AS LUONGCB
	FROM NHANVIEN
	CLOSE SYMMETRIC KEY SK01;
END

EXEC SP_SEL_NHANVIEN

ALTER PROCEDURE SP_Login
    @Username NVARCHAR(50),
    @Password NVARCHAR(50),
    @IsValid BIT OUTPUT
AS
BEGIN
    DECLARE @MATKHAU_HASH NVARCHAR(50)
    DECLARE @ROLE NVARCHAR(50)

    -- Kiểm tra tên đăng nhập và mật khẩu trong bảng SINHVIEN
    SELECT @MATKHAU_HASH = MATKHAU, @ROLE = 'SINHVIEN'
    FROM SINHVIEN
    WHERE TENDN = @Username

    IF @MATKHAU_HASH IS NOT NULL
    BEGIN
        IF @MATKHAU_HASH = CONVERT(varbinary(16), HASHBYTES('MD5', @Password), 1)
        BEGIN
            SET @IsValid = 1
            RETURN
        END
    END

    -- Kiểm tra tên đăng nhập và mật khẩu trong bảng NHANVIEN
    SELECT @MATKHAU_HASH = MATKHAU, @ROLE = 'NHANVIEN'
    FROM NHANVIEN
    WHERE TENDN = @Username

    IF @MATKHAU_HASH IS NOT NULL
    BEGIN
        IF @MATKHAU_HASH = CONVERT(varbinary(16), HASHBYTES('SHA1', @Password), 1)
        BEGIN
            SET @IsValid = 1
            RETURN
        END
    END

    SET @IsValid = 0
END